# Generated by Django 5.0.6 on 2024-05-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('1А', '1А'), ('2Б', '2Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Зима')),
                ('summer', models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('1А', '1А'), ('2Б', '2Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Лето')),
                ('autumn', models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('1А', '1А'), ('2Б', '2Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Осень')),
                ('spring', models.CharField(choices=[('1Б', '1Б'), ('2А', '2А'), ('3Б', '3Б'), ('1А', '1А'), ('2Б', '2Б'), ('3А', '3А')], default='1А', max_length=2, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('otc', models.CharField(max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('accepted', 'Принят'), ('new', 'Новый'), ('rejected', 'Отклонён'), ('pending', 'В работе')], default='new', max_length=8)),
                ('beauty_title', models.CharField(default='пер.', max_length=255)),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Альтернативное название')),
                ('connect', models.TextField(max_length=500, verbose_name='Что соединяет')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('coords', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level', verbose_name='Сложность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.users', verbose_name='Автор')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=2000)),
                ('title', models.CharField(max_length=255)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval')),
            ],
        ),
    ]
